### ISSUE TITLE
How to load crate by path?

### ISSUE THREAD

**Issue by astrojhgu** [google/evcxr#35] opened 2018-12-07 15:09 UTC
In Cargo.toml, one can specify dependencies by path:
```hello_utils = { path = "hello_utils" }```

But this seems not working in repl.
```
:dep hello_utils = { path = "hello_utils" }
```
will cause an error.

**Comment by davidlattimore** [comment] 2018-12-08 09:34
Thanks for reporting this. As a temporary workaround, it should work if you give it an absolute path. I'll close now as a duplicate of #14 and go and fix it. Thanks for the prompt, this had kind of slipped my mind.

**Closed by davidlattimore** 2018-12-08 09:34 UTC
